-- AlterTable
ALTER TABLE "projects" ALTER COLUMN "cost" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "votes" SET DATA TYPE DECIMAL(65,30);

-- AlterTable
ALTER TABLE "users" ALTER COLUMN "PESEL" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "phone" SET DATA TYPE DECIMAL(65,30);
